baseurl = "https://gaysianthirdspace.com/"
defaultContentLanguage = "en"
disqusShortname = ""
googleAnalytics = "UA-77731767-2"
languageCode = "en-us"
paginate = 10
theme = "hugo-universal-theme"
title = "GaysianThirdSpace"
[Permalinks]
blog = "/blog/:year/:month/:day/:filename/"
[blackfriday]
hrefTargetBlank = true
[[menu.footerbar]]
name = "Instagram"
pre = "<i class='fa fa-instagram'></i>"
url = "//instagram.com/gaysianthirdspace"
weight = 3
[[menu.footerbar]]
name = "Facebook"
pre = "<i class='fa fa-facebook'></i>"
url = "//facebook.com/gaysianthirdspace"
weight = 2
[[menu.footerbar]]
name = "Tumblr"
pre = "<i class='fa fa-tumblr'></i>"
url = "//gaysianthirdspace.tumblr.com"
weight = 1
[[menu.footerbar]]
name = "Email"
pre = "<i class='fa fa-envelope'></i>"
url = "mailto:gaysianthirdspace@gmail.com"
weight = 4
[[menu.main]]
name = "Blog"
url = "//gaysianthirdspace.tumblr.com"
weight = 4
[[menu.main]]
name = "About"
url = "/about/"
weight = 1
[[menu.main]]
identifier = "programs"
name = "Programs"
url = "/programs/"
weight = 2
[[menu.main]]
identifier = "meetups"
name = "Meetups"
url = "/meetups/"
weight = 3
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 5
[params]
author = "Gaysian Third Space"
copyright = "Copyright © 2017 Gaysian Third Space, All Rights Reserved."
date_format = "January 2, 2006"
defaultdescription = "Outside the clubs and beyond the apps, we aim to provide a Third Space – a community to share, discuss, and provide support for the unique experience of being Gay and Asian. Get involved in our community and make some new friends!"
defaultkeywords = ["gaysian", "gay", "asian", "asian american", "queer", "lgbt", "lgbtq", "community"]
email = "gaysianthirdspace@gmail.com"
googlemapsapikey = "AIzaSyANBtYpVRcaEEOn3wq8CBvhGQdHysVk4wU"
latitude = "-12.043333"
logo = "img/logo.png"
longitude = "-77.028333"
style = "orange"
viewmorepostlink = "/blog/"
[params.carousel]
enable = true
[params.footerbar]
enable = true
[params.partners]
enable = false
subtitle = ""
title = "Partner Organizations"
[params.recent_posts]
enable = false
subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
title = "From our blog"
[params.see_more]
enable = false
icon = "fa fa-file-code-o"
link_text = "Check other homepages"
link_url = "#"
subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
title = "Do you want to see more?"
[params.testimonials]
enable = false
subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."
title = "Testimonials"
[params.topbar]
enable = false
text = "<p class=\"hidden-sm hidden-xs\">Contact us on +420 777 555 333 or hello@universal.com.</p>\n      <p class=\"hidden-md hidden-lg\"><a href=\"#\" data-animate-hover=\"pulse\"><i class=\"fa fa-phone\"></i></a>\n      <a href=\"#\" data-animate-hover=\"pulse\"><i class=\"fa fa-envelope\"></i></a>\n      </p>\n      "
[params.values]
enable = true
[params.widgets]
categories = true
search = true
tags = true
